name: ldslockOS Build Factory
on: [push]

jobs:
  generate-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ldslockOS Source
        uses: actions/checkout@v4

      - name: Install Compilers and Tools
        run: |
          sudo apt update
          sudo apt install -y live-build nasm mono-devel build-essential dirmngr

      - name: Compile OS Components
        run: |
          # 1. CRIAR A PASTA DE BINÁRIOS (O erro estava aqui!)
          mkdir -p src/bin
          
          # 2. COMPILAR ASSEMBLY
          nasm -f elf64 src/boot/header.asm -o src/bin/header.o
          
          # 3. COMPILAR C++
          g++ -c src/kernel_ext/info.cpp -o src/bin/info.o
          
          # 4. COMPILAR C# (LOCK MANAGER)
          mcs src/tools/Manager.cs -out:src/bin/LockManager.exe

      - name: Build ldslockOS ISO
        run: |
          mkdir build && cd build
          lb config --distribution testing \
                    --architectures amd64 \
                    --bootloader grub-pc \
                    --archive-areas "main contrib non-free non-free-firmware"

          # Configurando pacotes e instalador
          mkdir -p config/package-lists
          echo "locales console-setup" > config/package-lists/languages.list.chroot
          echo "linux-image-amd64 mono-runtime i3-wm i3status rofi xorg" > config/package-lists/core.list.chroot
          echo "gnome-control-center gnome-settings-daemon network-manager-gnome calamares-settings-debian calamares" > config/package-lists/ui.list.chroot

          # Inserindo o seu Gerenciador C# dentro da ISO
          mkdir -p config/includes.chroot/usr/local/bin
          cp ../src/bin/LockManager.exe config/includes.chroot/usr/local/bin/
          
          sudo lb build

      - name: Release ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ldslockOS-Alpha-Build
          path: build/*.iso
