- name: Build ldslockOS ISO
        run: |
          mkdir -p build && cd build
          
          # Forçando o mirror oficial do Debian para não usar o do Ubuntu
          lb config --distribution testing \
                    --architectures amd64 \
                    --bootloader grub-pc \
                    --mirror-bootstrap "http://deb.debian.org/debian/" \
                    --mirror-chroot "http://deb.debian.org/debian/" \
                    --mirror-binary "http://deb.debian.org/debian/" \
                    --archive-areas "main contrib non-free non-free-firmware"

          # Criando as listas de pacotes
          mkdir -p config/package-lists
          echo "linux-image-amd64 mono-runtime i3-wm xorg rofi" > config/package-lists/my-os.list.chroot
          echo "calamares calamares-settings-debian" > config/package-lists/installer.list.chroot

          # Inserindo seu Manager
          mkdir -p config/includes.chroot/usr/bin
          cp ../src/bin/LockManager.exe config/includes.chroot/usr/bin/
          
          # Rodando o build com sudo
          sudo lb build


